name: csplookup
version: 0.9.6
homepage: https://github.com/Navid2zp/csplookup-dart
description: Dart client package for CSP Lookup API. Requires an API key from CSP platform.

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  http: ^0.12.0+4