name: csplookup
version: 0.9.0
homepage: https://github.com/Navid2zp/csplookup-dart
description: Client package for CSP Lookup API.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.12.0+4